// <auto-generated />
using System;
using HouseBills.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseBills.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("HouseBills.Domain.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PaidAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecurringBillId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DueDate");

                    b.HasIndex("PayeeId");

                    b.HasIndex("RecurringBillId", "DueDate")
                        .IsUnique();

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("HouseBills.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Utilities",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 }
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rent / Mortgage",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 }
                        },
                        new
                        {
                            Id = 3,
                            Name = "Internet & Phone",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 }
                        },
                        new
                        {
                            Id = 4,
                            Name = "Insurance",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 }
                        },
                        new
                        {
                            Id = 5,
                            Name = "Taxes & Fees",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 }
                        },
                        new
                        {
                            Id = 6,
                            Name = "Subscriptions",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 }
                        },
                        new
                        {
                            Id = 7,
                            Name = "Other",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 }
                        });
                });

            modelBuilder.Entity("HouseBills.Domain.Payee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountReference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Payees", (string)null);
                });

            modelBuilder.Entity("HouseBills.Domain.RecurringBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("GeneratedThrough")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PayeeId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PayeeId");

                    b.ToTable("RecurringBills", (string)null);
                });

            modelBuilder.Entity("HouseBills.Domain.Bill", b =>
                {
                    b.HasOne("HouseBills.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HouseBills.Domain.Payee", null)
                        .WithMany()
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HouseBills.Domain.RecurringBill", null)
                        .WithMany()
                        .HasForeignKey("RecurringBillId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("HouseBills.Domain.RecurringBill", b =>
                {
                    b.HasOne("HouseBills.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HouseBills.Domain.Payee", null)
                        .WithMany()
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
